apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels: # this is for replcaset
    app: App1
    function: Front-end
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App1
  template:
    metadata:
      labels: # this is for pod template
        app: App1
        function: Front-end
    spec:
      containers:
        - name: simple-webapp
          image: simple-webapp
