apiVersion: v1
kind: Pod
metadata:
  name: yellow
spec:
  containers:
    - name: lemon
      image: busybox
      command: ["sleep", "1000"]   # prevents CrashLoopBackOff
    - name: gold
      image: redis
