apiVersion: v1
kind: Secret
metadata:
  name: db-secret              # 👈 Secret name
type: Opaque                   # 👈 Type of secret (Opaque = generic key/value)
stringData:                    # 👈 Human-readable, auto-base64 encoded
  DB_Host: sql01               # 👈 Example DB host
  DB_User: root                # 👈 Example DB username
  DB_Password: xyz             # 👈 Demo password placeholder (never commit real creds!)
